// <auto-generated />
using System;
using Locatic.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Locatic.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613222127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("Locatic.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryOfOrigin = "France",
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 2,
                            CountryOfOrigin = "France",
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 3,
                            CountryOfOrigin = "Germany",
                            Name = "BMW"
                        });
                });

            modelBuilder.Entity("Locatic.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarModelId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FuelType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarModelId = 1,
                            DailyRate = 45m,
                            FuelType = 0,
                            LicensePlate = "AB-123-CD",
                            SeatsCount = 5,
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            CarModelId = 3,
                            DailyRate = 55m,
                            FuelType = 1,
                            LicensePlate = "EF-456-GH",
                            SeatsCount = 5,
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            CarModelId = 5,
                            DailyRate = 90m,
                            FuelType = 3,
                            LicensePlate = "IJ-789-KL",
                            SeatsCount = 5,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("Locatic.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "Clio"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "Megane"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            Name = "208"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            Name = "3008"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            Name = "Série 3"
                        });
                });

            modelBuilder.Entity("Locatic.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice.martin@email.fr",
                            FirstName = "Alice",
                            LastName = "Martin",
                            Phone = "0601020304"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob.dupont@email.fr",
                            FirstName = "Bob",
                            LastName = "Dupont",
                            Phone = "0605060708"
                        });
                });

            modelBuilder.Entity("Locatic.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Locatic.Models.Car", b =>
                {
                    b.HasOne("Locatic.Models.CarModel", "CarModel")
                        .WithMany("Cars")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("Locatic.Models.CarModel", b =>
                {
                    b.HasOne("Locatic.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Locatic.Models.Reservation", b =>
                {
                    b.HasOne("Locatic.Models.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locatic.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Locatic.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Locatic.Models.Car", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Locatic.Models.CarModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Locatic.Models.Client", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
