apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "locatic.fullname" . }}
  labels:
    {{- include "locatic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "locatic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "locatic.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.config.appPort | quote }}
        prometheus.io/path: /metrics
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1654
        fsGroup: 1654
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.appPort }}
          envFrom:
            - configMapRef:
                name: {{ include "locatic.fullname" . }}-config
          env:
            - name: DB_PATH
              value: {{ .Values.sqlite.dbPath | quote }}
          volumeMounts:
            - name: sqlite-data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.config.appPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.config.appPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: {{ .Values.sqlite.existingClaim }}
