{{- if and .Values.ingress.enabled .Values.nginx.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "locatic.fullname" . }}
  labels:
    {{- include "locatic.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "locatic.fullname" . }}-nginx
                port:
                  number: 80
{{- end }}
